[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; 
lib_deps = 
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.3
    bblanchon/ArduinoJson@^6.21.3
    links2004/WebSockets@^2.3.6
; 


board_build.partitions = default.csv
build_unflags = -std=gnu++11
build_flags = 
    -Iinclude
    -Wno-unused-function
    -ffunction-sections
    -fdata-sections
    -DSSD1306_128_64
    -Wno-macro-redefined

monitor_port = 
upload_port = 